name: Crowdin translation download

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build i18n application
        run: "./gradlew i18n:build"
      - name: Generate translation source
        run: "java -jar i18n/build/libs/i18n-all.jar"
      - name: Download translations from Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_sources: false
          download_translations: true
          download_translations_args: "--verbose"

          localization_branch_name: i18n
          create_pull_request: true
          commit_message: "New Crowdin translations"
          pull_request_title: "New Crowdin translations"
          pull_request_base_branch_name: "main"

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: "i18n/build/source.json"
          translation: "/i18n/src/main/resources/translations/%two_letters_code%.%file_extension%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
